"""empty message

Revision ID: 57f9d121337d
Revises: a626a019ab58
Create Date: 2026-02-17 18:39:06.230908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57f9d121337d'
down_revision: Union[str, Sequence[str], None] = 'a626a019ab58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('percent', sa.Numeric(), nullable=True))
    op.drop_column('plan', 'precent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('precent', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('plan', 'percent')
    # ### end Alembic commands ###
