"""empty message

Revision ID: a626a019ab58
Revises: af13d2363959
Create Date: 2026-02-17 18:16:38.357823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a626a019ab58'
down_revision: Union[str, Sequence[str], None] = 'af13d2363959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plan', 'precent',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.drop_column('plan', 'is_global')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('is_global', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.alter_column('plan', 'precent',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###
