"""empty message

Revision ID: d2a701098fa6
Revises: 5e5d8b55ed6a
Create Date: 2026-05-18 02:31:58.832843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2a701098fa6'
down_revision: Union[str, Sequence[str], None] = '5e5d8b55ed6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('date_create', sa.DateTime(), nullable=True))
    op.add_column('category', sa.Column('date_upd_cat_sum', sa.DateTime(), nullable=True))
    op.add_column('plan', sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan', 'date')
    op.drop_column('category', 'date_upd_cat_sum')
    op.drop_column('category', 'date_create')
    # ### end Alembic commands ###
