"""deleted parent_id from category model

Revision ID: 0fd5781e2326
Revises: 119528a07bd9
Create Date: 2026-05-18 02:23:19.735833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fd5781e2326'
down_revision: Union[str, Sequence[str], None] = '119528a07bd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('category_parent_id_fkey'), 'category', type_='foreignkey')
    op.drop_column('category', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('category_parent_id_fkey'), 'category', 'category', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
