"""added cat_sum for category model

Revision ID: da370cd8d39b
Revises: 57f9d121337d
Create Date: 2026-02-21 21:52:31.118105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da370cd8d39b'
down_revision: Union[str, Sequence[str], None] = '57f9d121337d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('cat_sum', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'cat_sum')
    # ### end Alembic commands ###
